### ISSUE TITLE
Add parameter for the proxy

### ISSUE THREAD

**Issue by vfarcic** [bvis/docker-node-exporter#1]
I think it would be useful to add the "proxy service name" parameter on dashboard import. The alternative would be to use a more generic hardcoded name like "proxy".

P.S. It's a great dashboard. I'm planning to include it in https://leanpub.com/the-devops-2-1-toolkit.

**Comment by bvis** [comment]
Of course, I think that more generic name like "proxy" would be good, by now I've moved the hardcoded value to a variable that can be selected to filter the value, now you can select your desired service/s to exclude from traffic metrics.

**Comment by vfarcic** [comment]
Works like a charm.

P.S. I just published a new chapter in [https://leanpub.com/the-devops-2-1-toolkit](https://leanpub.com/the-devops-2-1-toolkit) and your dashboard has a prominent place in it.

**Comment by bvis** [comment]
Thanks. ;)
