### ISSUE TITLE
How do I get the host name when creating an alert?

### ISSUE THREAD

**Issue by byrnedo** [bvis/docker-node-exporter#2]
How can I get the host then as part of a summary or description in an alert?
Eg. Can I just reference $labels.host in the following or do I need to do some kind of relabel ?
```
ALERT service_down
  IF up == 0
  FOR 30s
  LABELS { severity = "critical" }
  ANNOTATIONS {
      summary = "'{{ $labels.job }}'/'{{ $labels.host }}' Service is down",
      description = "Service '{{ $labels.job }}', instance '{{ $labels.instance }}' is down.",
  }
```
Or do I need to do something like this to get the value?
```
 {{ printf `host{instance="%s"}` $labels.instance | query | first }}
```

**Comment by byrnedo** [comment]
@bvis Any ideas?

**Comment by bvis** [comment]
Hi @byrnedo,

Unfortunately I've not found a way to do it. As it's using DNS service discovery we are so limited in features.

In a future I hope Prometheus will integrate a direct integration with Swarm that will provide nice relabelling features.

If you have ideas about how to do it, it would be awesome.

**Comment by byrnedo** [comment]
I actually got around it using the service templating that was introduced in docker 1.13.

Basically I added that the service gets `hostname: "{{.Swarm.NodeID}}"` and then the `docker-entrypoint.sh` you have would look like this:
```
echo "host{host=\"$host_hostname\",node=\"$(hostname)\"} 1" > /etc/node-exporter/host_hostname.prom
```

I actually ended up putting something resembling this on the node's cronjobs instead but same idea.

Then I 'should' be able to query it using the node id.

**Comment by bvis** [comment]
Mmm, nice idea, I'll give it a try!

**Comment by byrnedo** [comment]
actually, nevermind, I didn't even have to do that. One can use the 'group_left' function like so:

```
(predict_linear(node_filesystem_free{mountpoint="/"}[1h], 8 * 3600) < 0) * ON(instance) GROUP_LEFT(host) host
```
So basically: 
```
(<any check>) * ON(instance) GROUP_LEFT(host) host
```
will work and merge the host label into the result.

**Comment by bvis** [comment]
Ok, maybe you could provide a PR with this improvement, it would be amazing.

**Comment by bvis** [comment]
Hi, I've applied the changes you suggested. They work! Thanks a lot.

I'll close this issue, if you need anything else feel free to reopen this issue at any moment.

**Comment by byrnedo** [comment]
Sorry, I forgot all about this. Thanks for taking it up and doing it anyway!
